### ISSUE TITLE
1.4.0 bugs (please add every new bug as a separate comment)

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1765]
To test - go to https://vuestic.dev

**Comment by RVitaly1978** [comment]
- [ ] date-input validation not working

**Comment by RVitaly1978** [comment]
- [x] update `VaAvatar` docs examples (PR #1767)
- [x] fix `VaChip` color with link prop in docs (PR #1767)
- [x] fix `ratio` type (string to number) in `VaImage` docs example (PR #1767)

**Comment by m0ksem** [comment]
- Change buildModules to modules.

https://vuestic.dev/en/getting-started/nuxt


- Move accessibility guide to introduction instead of getting started?

- Button group text colors are weird. https://vuestic.dev/en/ui-elements/button-toggle#colors
(This must be fixed in useTextColor issue, so it is already in progress)

- Chip link takes classes from typography.
https://vuestic.dev/en/ui-elements/chip#link

Typography must be independent.

- Button group component doesn't fit mobile screen.
https://vuestic.dev/en/ui-elements/icon#rotation-and-flip

- Can't see text in input on mobile.
https://vuestic.dev/en/ui-elements/counter#slots

- VaDatePicker first element is focused for some reason. Must be focused after some trigger.
https://vuestic.dev/en/ui-elements/date-input#basic-usage

- Minor. Android phone adds thing for select text, but text can bot be selected. (@m0ksem add screenshots later!!)
https://vuestic.dev/en/ui-elements/select#state

- TimePicker focus last TimePicker's first element.
https://vuestic.dev/en/ui-elements/time-picker

**Comment by m0ksem** [comment]
- Fix accordion (PR already exists)

- Sidebar demo has broken color. Must be fixed with useTextColor. (Or likely broken demo)
 - Same color problem text with gradient cards.
Think about two above like them in progress.

- Demo to small https://vuestic.dev/en/ui-elements/tabs#color

- Slot based access demo doesn't work on mobile https://vuestic.dev/en/ui-elements/hover#slot-based-access

**Comment by m0ksem** [comment]
Search broken 
![image](https://user-images.githubusercontent.com/23530004/168262526-583ae877-ae3a-48d0-9929-d982d49d5afa.png)

And looks like sidebar text color is not primary.

**Comment by m0ksem** [comment]
https://codesandbox.io/s/smoosh-glade-umrmj3

Codesandbox not working in firefox.

**Comment by RVitaly1978** [comment]
- [x] there's no import `va-icon` in `va-collapse` (PR #1777 )
