### ISSUE TITLE
Nuxt docs known bugs

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2981]
Visit: https://develop.vuestic.dev/en

Issues: 

High priority
- [x] #2988
- [x] #2985

Middle:
- [x] #2990
- [x] #2989
- [x] #2991
- [x] #2987
- [x] Missing Epicmax banner + (https://github.com/epicmaxco/vuestic-ui/issues/2912)
- [x] #2992
- [x] #2993
- [ ] #3002

Minor (minor, but easy to do):
- [x] Update Roadmap images (https://github.com/epicmaxco/vuestic-ui/issues/2966)
- [x] Update alert stlyle (https://github.com/epicmaxco/vuestic-ui/issues/2962 + PR)
- [x] Update code style (https://github.com/epicmaxco/vuestic-ui/issues/2947 @m0ksem partially made)
- [x] Update colors (https://github.com/epicmaxco/vuestic-ui/issues/2940 + PR)
- [x] #2994
- [x] Landing layout issues (https://github.com/epicmaxco/vuestic-ui/issues/2978)
- [x] #2986
- [x] #2995
- [x] #2996

Likely deferred:
- [ ] #3056
- [ ] Ru translation sync (I would do this after https://github.com/epicmaxco/vuestic-ui/issues/2970)

Deferred:
- [ ] i18n messages code split (https://github.com/epicmaxco/vuestic-ui/issues/2970)
- [ ] #2998
- [ ] #2997

**Comment by zvenigorodskaia** [comment]
https://develop.vuestic.dev/en/extensions/ag-grid 
![image](https://user-images.githubusercontent.com/35342240/219316532-e94c58a1-e38e-42c3-916e-35ec00d9adc0.png)

**Comment by asvae** [comment]
Let's close this issue somehow, it lived long enough.

**Comment by m0ksem** [comment]
I would close it and use separate issues.
