### ISSUE TITLE
Update roadmap

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#3091]
[Roadmap page](https://vuestic.dev/introduction/roadmap) is outdated.

- [ ] We need to create a 1.6 section (you can grab info from [here](https://github.com/epicmaxco/vuestic-ui/releases/tag/v1.6.0)), be sure to include stepper and skeleton
- [ ] Move 1.5 and 1.6 to released
- [ ] Outline some plans for 1.7 (vuestic-admin etc)

**Comment by m0ksem** [comment]
I would remake our roadmap style. It is hard to make images and we don't want to wait until they're done.
